#!/bin/bash

# Script to help get detailed error from Strapi logs
# The Apache logs show 500 but not the actual error

echo "🔍 Getting Strapi Error Details"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Apache logs show 500 errors, but we need Strapi application logs"
echo "to see the actual error message."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Where to find Strapi logs:"
echo ""
echo "1️⃣ Via Plesk:"
echo "   - Log into Plesk"
echo "   - Go to Domains → cms.envicon.nl → Node.js"
echo "   - Click 'View Logs' or 'Application Logs'"
echo "   - Look for errors around 17:09-17:11 (when 500s occurred)"
echo ""
echo "2️⃣ Via Plesk File Manager:"
echo "   - Go to Files → File Manager"
echo "   - Navigate to your Strapi directory"
echo "   - Check logs/ folder:"
echo "     - strapi.log"
echo "     - strapi-output.log"
echo "     - strapi-startup.log"
echo ""
echo "3️⃣ Via SSH (if available):"
echo "   cd /var/www/vhosts/envicon.nl/cms.envicon.nl/httpdocs"
echo "   tail -100 logs/*.log | grep -A 10 -B 10 'error\|Error\|ERROR'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "What to look for:"
echo "  - Error messages mentioning 'publishedAt'"
echo "  - Database constraint errors"
echo "  - Validation errors"
echo "  - Stack traces showing the exact failing code"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Common errors you might see:"
echo ""
echo "1. Database constraint:"
echo "   'NOT NULL constraint failed: articles.publishedAt'"
echo "   → Fix: ALTER TABLE articles MODIFY publishedAt DATETIME NULL;"
echo ""
echo "2. Validation error:"
echo "   'publishedAt is required'"
echo "   → Fix: Verify schema file has required: false"
echo ""
echo "3. Type mismatch:"
echo "   'Invalid date format'"
echo "   → Fix: Check publishedAt type in schema"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

